#!/usr/bin/env python3
"""Regenerates the test patches and banks in this folder.

Vital's factory presets can't be redistributed, so the tests use patches
made here: the init patch saved by sloppy-render, with settings and
modulations edited the way Vital itself would write them.

Usage: make_fixtures.py path/to/sloppy-render
"""
import copy
import io
import json
import os
import subprocess
import sys
import tempfile
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))


def save_init_patch(render):
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "init.vital")
        subprocess.run([render, "--save", path], check=True, stderr=subprocess.DEVNULL)
        with open(path) as f:
            return json.load(f)


def write_patch(name, patch):
    with open(os.path.join(HERE, name), "w") as f:
        json.dump(patch, f, separators=(",", ":"))


def add_modulation(patch, index, source, destination, amount):
    settings = patch["settings"]
    settings["modulations"][index - 1] = {"source": source, "destination": destination}
    settings["modulation_%d_amount" % index] = amount


def bass_patch(init):
    patch = copy.deepcopy(init)
    patch["preset_name"] = "Test Bass"
    patch["author"] = "sloppy-synth tests"
    patch["preset_style"] = "Bass"
    patch["comments"] = "Generated by tests/fixtures/make_fixtures.py"
    s = patch["settings"]
    s.update({
        "osc_1_unison_voices": 4.0,
        "osc_1_unison_detune": 3.0,
        "osc_1_wave_frame": 64.0,
        "osc_2_on": 1.0,
        "osc_2_transpose": -12.0,
        "osc_2_level": 0.5,
        "filter_1_on": 1.0,
        "filter_1_model": 1.0,
        "filter_1_cutoff": 70.0,
        "filter_1_resonance": 0.6,
        "env_1_release": 0.4,
        "chorus_on": 1.0,
        "delay_on": 1.0,
        "reverb_on": 1.0,
        "distortion_on": 1.0,
        "polyphony": 8.0,
    })
    add_modulation(patch, 1, "lfo_1", "filter_1_cutoff", 0.3)
    add_modulation(patch, 2, "env_2", "osc_1_wave_frame", 0.5)
    add_modulation(patch, 3, "macro_control_1", "filter_1_resonance", 0.25)
    return patch


def pad_patch(init):
    patch = copy.deepcopy(init)
    patch["preset_name"] = "Test Pad"
    patch["author"] = "sloppy-synth tests"
    patch["preset_style"] = "Pad"
    s = patch["settings"]
    s.update({
        "osc_1_unison_voices": 8.0,
        "osc_1_spectral_morph_type": 2.0,
        "osc_1_spectral_morph_amount": 0.4,
        "env_1_attack": 0.8,
        "env_1_release": 1.2,
        "filter_2_on": 1.0,
        "filter_2_model": 4.0,
        "phaser_on": 1.0,
        "reverb_on": 1.0,
        "reverb_dry_wet": 0.4,
    })
    add_modulation(patch, 1, "lfo_2", "osc_1_spectral_morph_amount", 0.2)
    return patch


def write_bank(name, bank_folder, patches, extra_entries=()):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as z:
        for category, patch in patches:
            path = "%s/Presets/%s%s.vital" % (bank_folder, category + "/" if category else "", patch["preset_name"])
            z.writestr(path, json.dumps(patch, separators=(",", ":")))
        for path, data in extra_entries:
            z.writestr(path, data)
    with open(os.path.join(HERE, name), "wb") as f:
        f.write(buffer.getvalue())


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    init = save_init_patch(sys.argv[1])
    bass = bass_patch(init)
    pad = pad_patch(init)

    write_patch("test_bass.vital", bass)

    # Saved by an older Vital 1.0.x: goes through LoadSave::updateFromOldVersion.
    older = copy.deepcopy(bass)
    older["synth_version"] = "1.0.7"
    older["preset_name"] = "Test Bass 1.0"
    write_patch("test_bass_v1_0.vital", older)

    # From a future major.minor version: Vital refuses these, and so do we.
    newer = copy.deepcopy(bass)
    newer["synth_version"] = "9.0.0"
    write_patch("from_the_future.vital", newer)

    write_bank("Test Bank.vitalbank", "Test Bank", [("Bass", bass), ("Pads", pad), ("", older)])

    # A malicious bank: must be rejected without writing anything.
    write_bank("zip_slip.vitalbank", "Evil", [("", bass)], [("../escaped.txt", "nope")])


if __name__ == "__main__":
    main()
