#!/usr/bin/env python3
"""Regenerates the test patches and banks in this folder.

Vital's factory presets can't be redistributed, so the tests use patches
made here: the init patch saved by sloppy-render, with settings and
modulations edited the way Vital itself would write them.

Usage: make_fixtures.py path/to/sloppy-render
"""
import copy
import io
import json
import os
import subprocess
import sys
import tempfile
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))


def save_init_patch(render):
    with tempfile.TemporaryDirectory() as tmp:
        path = os.path.join(tmp, "init.vital")
        subprocess.run([render, "--save", path], check=True, stderr=subprocess.DEVNULL)
        with open(path) as f:
            return json.load(f)


def write_patch(name, patch):
    with open(os.path.join(HERE, name), "w") as f:
        json.dump(patch, f, separators=(",", ":"))


def add_modulation(patch, index, source, destination, amount):
    settings = patch["settings"]
    settings["modulations"][index - 1] = {"source": source, "destination": destination}
    settings["modulation_%d_amount" % index] = amount


def bass_patch(init):
    patch = copy.deepcopy(init)
    patch["preset_name"] = "Test Bass"
    patch["author"] = "sloppy-synth tests"
    patch["preset_style"] = "Bass"
    patch["comments"] = "Generated by tests/fixtures/make_fixtures.py"
    s = patch["settings"]
    s.update({
        "osc_1_unison_voices": 4.0,
        "osc_1_unison_detune": 3.0,
        "osc_1_wave_frame": 64.0,
        "osc_2_on": 1.0,
        "osc_2_transpose": -12.0,
        "osc_2_level": 0.5,
        "filter_1_on": 1.0,
        "filter_1_model": 1.0,
        "filter_1_cutoff": 70.0,
        "filter_1_resonance": 0.6,
        "env_1_release": 0.4,
        "chorus_on": 1.0,
        "delay_on": 1.0,
        "reverb_on": 1.0,
        "distortion_on": 1.0,
        "polyphony": 8.0,
    })
    add_modulation(patch, 1, "lfo_1", "filter_1_cutoff", 0.3)
    add_modulation(patch, 2, "env_2", "osc_1_wave_frame", 0.5)
    add_modulation(patch, 3, "macro_control_1", "filter_1_resonance", 0.25)
    return patch


def pad_patch(init):
    patch = copy.deepcopy(init)
    patch["preset_name"] = "Test Pad"
    patch["author"] = "sloppy-synth tests"
    patch["preset_style"] = "Pad"
    s = patch["settings"]
    s.update({
        "osc_1_unison_voices": 8.0,
        "osc_1_spectral_morph_type": 2.0,
        "osc_1_spectral_morph_amount": 0.4,
        "env_1_attack": 0.8,
        "env_1_release": 1.2,
        "filter_2_on": 1.0,
        "filter_2_model": 4.0,
        "phaser_on": 1.0,
        "reverb_on": 1.0,
        "reverb_dry_wet": 0.4,
    })
    add_modulation(patch, 1, "lfo_2", "osc_1_spectral_morph_amount", 0.2)
    return patch


def newer_minor_patch(bass):
    patch = copy.deepcopy(bass)
    patch["synth_version"] = "1.6.4"
    patch["preset_name"] = "Test Bass 1.6"
    s = patch["settings"]
    s["osc_1_spectral_morph_type"] = 13.0  # past the end of this engine's list
    s["osc_1_made_up_seed"] = 0.5
    s["lfos"][0]["made_up_ramp"] = 0.25
    add_modulation(patch, 4, "made_up_source", "filter_1_cutoff", 0.4)
    # Vital 1.5 renumbered unison stack styles: 5 is "2x Octave" (4 here),
    # 4 is the new "Octave + 7".
    s["osc_2_stack_style"] = 5.0
    s["osc_3_stack_style"] = 4.0
    # The formant filter's vocal tract style: silent in the public source.
    s.update({"filter_2_on": 1.0, "filter_2_model": 5.0, "filter_2_style": 2.0})
    # Settings Vital 1.6.4 writes into every patch, at their defaults.
    patch["tuning"] = {"default": True, "mapping_name": "", "reference_midi_note": 0.0,
                       "scale": [float(i) for i in range(13)], "scale_start_midi_note": 60,
                       "tuning_name": ""}
    for i in range(1, 65):
        s["modulation_%d_ramp_up" % i] = -10.0
        s["modulation_%d_ramp_down" % i] = -10.0
    for i in range(1, 4):
        s["osc_%d_spectral_morph_phase" % i] = 0.5
    triangle = {"name": "Triangle", "num_points": 3, "points": [0.0, 1.0, 0.5, 0.0, 1.0, 1.0],
                "powers": [0.0, 0.0, 0.0], "smooth": False}
    s["custom_warps"] = [triangle] * 3
    s["random_values"] = [{"seed": 4}] * 3
    return patch


def write_bank(name, bank_folder, patches, extra_entries=()):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as z:
        for category, patch in patches:
            path = "%s/Presets/%s%s.vital" % (bank_folder, category + "/" if category else "", patch["preset_name"])
            z.writestr(path, json.dumps(patch, separators=(",", ":")))
        for path, data in extra_entries:
            z.writestr(path, data)
    with open(os.path.join(HERE, name), "wb") as f:
        f.write(buffer.getvalue())


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    init = save_init_patch(sys.argv[1])
    bass = bass_patch(init)
    pad = pad_patch(init)

    write_patch("test_bass.vital", bass)

    # Saved by an older Vital 1.0.x: goes through LoadSave::updateFromOldVersion.
    older = copy.deepcopy(bass)
    older["synth_version"] = "1.0.7"
    older["preset_name"] = "Test Bass 1.0"
    write_patch("test_bass_v1_0.vital", older)

    # From a future major.minor version: Vital refuses these, and so do we.
    newer = copy.deepcopy(bass)
    newer["synth_version"] = "9.0.0"
    write_patch("from_the_future.vital", newer)

    # From a newer 1.x release: loads, but what this engine lacks is reset or
    # skipped and reported. The new names are made up for the test.
    write_patch("from_vital_1_6.vital", newer_minor_patch(bass))

    write_bank("Test Bank.vitalbank", "Test Bank", [("Bass", bass), ("Pads", pad), ("", older)])

    # A malicious bank: must be rejected without writing anything.
    write_bank("zip_slip.vitalbank", "Evil", [("", bass)], [("../escaped.txt", "nope")])


if __name__ == "__main__":
    main()
